// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "mnist_lstm_Loop_1_pr.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic mnist_lstm_Loop_1_pr::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic mnist_lstm_Loop_1_pr::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> mnist_lstm_Loop_1_pr::ap_ST_fsm_state1 = "1";
const sc_lv<3> mnist_lstm_Loop_1_pr::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> mnist_lstm_Loop_1_pr::ap_ST_fsm_state19 = "100";
const sc_lv<32> mnist_lstm_Loop_1_pr::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool mnist_lstm_Loop_1_pr::ap_const_boolean_1 = true;
const sc_lv<32> mnist_lstm_Loop_1_pr::ap_const_lv32_1 = "1";
const bool mnist_lstm_Loop_1_pr::ap_const_boolean_0 = false;
const sc_lv<1> mnist_lstm_Loop_1_pr::ap_const_lv1_0 = "0";
const sc_lv<1> mnist_lstm_Loop_1_pr::ap_const_lv1_1 = "1";
const sc_lv<8> mnist_lstm_Loop_1_pr::ap_const_lv8_0 = "00000000";
const sc_lv<32> mnist_lstm_Loop_1_pr::ap_const_lv32_437F0000 = "1000011011111110000000000000000";
const sc_lv<8> mnist_lstm_Loop_1_pr::ap_const_lv8_E0 = "11100000";
const sc_lv<8> mnist_lstm_Loop_1_pr::ap_const_lv8_1 = "1";
const sc_lv<32> mnist_lstm_Loop_1_pr::ap_const_lv32_2 = "10";

mnist_lstm_Loop_1_pr::mnist_lstm_Loop_1_pr(sc_module_name name) : sc_module(name), mVcdFile(0) {
    LSTM_Top_fdiv_32nbkb_U1 = new LSTM_Top_fdiv_32nbkb<1,16,32,32,32>("LSTM_Top_fdiv_32nbkb_U1");
    LSTM_Top_fdiv_32nbkb_U1->clk(ap_clk);
    LSTM_Top_fdiv_32nbkb_U1->reset(ap_rst);
    LSTM_Top_fdiv_32nbkb_U1->din0(grp_fu_95_p0);
    LSTM_Top_fdiv_32nbkb_U1->din1(ap_var_for_const0);
    LSTM_Top_fdiv_32nbkb_U1->ce(grp_fu_95_ce);
    LSTM_Top_fdiv_32nbkb_U1->dout(grp_fu_95_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_r_TVALID );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond1_i_i_fu_100_p2 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_r_TVALID );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond1_i_i_fu_100_p2 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state18_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);
    sensitive << ( in_r_TVALID );
    sensitive << ( exitcond1_i_i_fu_100_p2 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond1_i_i_fu_100_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_ap_phi_mux_i_0_i_i_phi_fu_87_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( i_0_i_i_reg_83 );
    sensitive << ( exitcond1_i_i_reg_126 );
    sensitive << ( i_reg_130 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_exitcond1_i_i_fu_100_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_phi_mux_i_0_i_i_phi_fu_87_p4 );

    SC_METHOD(thread_grp_fu_95_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_95_p0);
    sensitive << ( in_r_TDATA );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_i_fu_106_p2);
    sensitive << ( ap_phi_mux_i_0_i_i_phi_fu_87_p4 );

    SC_METHOD(thread_img_dat_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( tmp_i_fu_121_p1 );

    SC_METHOD(thread_img_dat_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_img_dat_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_140 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_img_dat_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond1_i_i_reg_126_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_in_r_TDATA_blk_n);
    sensitive << ( in_r_TVALID );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond1_i_i_fu_100_p2 );

    SC_METHOD(thread_in_r_TREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond1_i_i_fu_100_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_i_fu_121_p1);
    sensitive << ( i_0_i_i_reg_83_pp0_iter15_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond1_i_i_fu_100_p2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter15 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter16 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "mnist_lstm_Loop_1_pr_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_TDATA, "(port)in_r_TDATA");
    sc_trace(mVcdFile, in_r_TVALID, "(port)in_r_TVALID");
    sc_trace(mVcdFile, in_r_TREADY, "(port)in_r_TREADY");
    sc_trace(mVcdFile, in_r_TSTRB, "(port)in_r_TSTRB");
    sc_trace(mVcdFile, in_r_TKEEP, "(port)in_r_TKEEP");
    sc_trace(mVcdFile, in_r_TUSER, "(port)in_r_TUSER");
    sc_trace(mVcdFile, in_r_TLAST, "(port)in_r_TLAST");
    sc_trace(mVcdFile, in_r_TID, "(port)in_r_TID");
    sc_trace(mVcdFile, in_r_TDEST, "(port)in_r_TDEST");
    sc_trace(mVcdFile, img_dat_address0, "(port)img_dat_address0");
    sc_trace(mVcdFile, img_dat_ce0, "(port)img_dat_ce0");
    sc_trace(mVcdFile, img_dat_we0, "(port)img_dat_we0");
    sc_trace(mVcdFile, img_dat_d0, "(port)img_dat_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, in_r_TDATA_blk_n, "in_r_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond1_i_i_fu_100_p2, "exitcond1_i_i_fu_100_p2");
    sc_trace(mVcdFile, i_0_i_i_reg_83, "i_0_i_i_reg_83");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter1_reg, "i_0_i_i_reg_83_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter11, "ap_block_state13_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter12, "ap_block_state14_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter13, "ap_block_state15_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter14, "ap_block_state16_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter15, "ap_block_state17_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage0_iter16, "ap_block_state18_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter2_reg, "i_0_i_i_reg_83_pp0_iter2_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter3_reg, "i_0_i_i_reg_83_pp0_iter3_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter4_reg, "i_0_i_i_reg_83_pp0_iter4_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter5_reg, "i_0_i_i_reg_83_pp0_iter5_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter6_reg, "i_0_i_i_reg_83_pp0_iter6_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter7_reg, "i_0_i_i_reg_83_pp0_iter7_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter8_reg, "i_0_i_i_reg_83_pp0_iter8_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter9_reg, "i_0_i_i_reg_83_pp0_iter9_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter10_reg, "i_0_i_i_reg_83_pp0_iter10_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter11_reg, "i_0_i_i_reg_83_pp0_iter11_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter12_reg, "i_0_i_i_reg_83_pp0_iter12_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter13_reg, "i_0_i_i_reg_83_pp0_iter13_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter14_reg, "i_0_i_i_reg_83_pp0_iter14_reg");
    sc_trace(mVcdFile, i_0_i_i_reg_83_pp0_iter15_reg, "i_0_i_i_reg_83_pp0_iter15_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126, "exitcond1_i_i_reg_126");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter1_reg, "exitcond1_i_i_reg_126_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter2_reg, "exitcond1_i_i_reg_126_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter3_reg, "exitcond1_i_i_reg_126_pp0_iter3_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter4_reg, "exitcond1_i_i_reg_126_pp0_iter4_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter5_reg, "exitcond1_i_i_reg_126_pp0_iter5_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter6_reg, "exitcond1_i_i_reg_126_pp0_iter6_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter7_reg, "exitcond1_i_i_reg_126_pp0_iter7_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter8_reg, "exitcond1_i_i_reg_126_pp0_iter8_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter9_reg, "exitcond1_i_i_reg_126_pp0_iter9_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter10_reg, "exitcond1_i_i_reg_126_pp0_iter10_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter11_reg, "exitcond1_i_i_reg_126_pp0_iter11_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter12_reg, "exitcond1_i_i_reg_126_pp0_iter12_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter13_reg, "exitcond1_i_i_reg_126_pp0_iter13_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter14_reg, "exitcond1_i_i_reg_126_pp0_iter14_reg");
    sc_trace(mVcdFile, exitcond1_i_i_reg_126_pp0_iter15_reg, "exitcond1_i_i_reg_126_pp0_iter15_reg");
    sc_trace(mVcdFile, i_fu_106_p2, "i_fu_106_p2");
    sc_trace(mVcdFile, i_reg_130, "i_reg_130");
    sc_trace(mVcdFile, grp_fu_95_p2, "grp_fu_95_p2");
    sc_trace(mVcdFile, tmp_2_i_reg_140, "tmp_2_i_reg_140");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter15, "ap_enable_reg_pp0_iter15");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter16, "ap_enable_reg_pp0_iter16");
    sc_trace(mVcdFile, ap_phi_mux_i_0_i_i_phi_fu_87_p4, "ap_phi_mux_i_0_i_i_phi_fu_87_p4");
    sc_trace(mVcdFile, tmp_i_fu_121_p1, "tmp_i_fu_121_p1");
    sc_trace(mVcdFile, grp_fu_95_p0, "grp_fu_95_p0");
    sc_trace(mVcdFile, grp_fu_95_ce, "grp_fu_95_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

mnist_lstm_Loop_1_pr::~mnist_lstm_Loop_1_pr() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete LSTM_Top_fdiv_32nbkb_U1;
}

void mnist_lstm_Loop_1_pr::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_437F0000;
}

void mnist_lstm_Loop_1_pr::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter15 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter15 = ap_enable_reg_pp0_iter14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter16 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter16 = ap_enable_reg_pp0_iter15.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter16 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_reg_126.read()))) {
        i_0_i_i_reg_83 = i_reg_130.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_i_i_reg_83 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond1_i_i_reg_126 = exitcond1_i_i_fu_100_p2.read();
        exitcond1_i_i_reg_126_pp0_iter1_reg = exitcond1_i_i_reg_126.read();
        i_0_i_i_reg_83_pp0_iter1_reg = i_0_i_i_reg_83.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond1_i_i_reg_126_pp0_iter10_reg = exitcond1_i_i_reg_126_pp0_iter9_reg.read();
        exitcond1_i_i_reg_126_pp0_iter11_reg = exitcond1_i_i_reg_126_pp0_iter10_reg.read();
        exitcond1_i_i_reg_126_pp0_iter12_reg = exitcond1_i_i_reg_126_pp0_iter11_reg.read();
        exitcond1_i_i_reg_126_pp0_iter13_reg = exitcond1_i_i_reg_126_pp0_iter12_reg.read();
        exitcond1_i_i_reg_126_pp0_iter14_reg = exitcond1_i_i_reg_126_pp0_iter13_reg.read();
        exitcond1_i_i_reg_126_pp0_iter15_reg = exitcond1_i_i_reg_126_pp0_iter14_reg.read();
        exitcond1_i_i_reg_126_pp0_iter2_reg = exitcond1_i_i_reg_126_pp0_iter1_reg.read();
        exitcond1_i_i_reg_126_pp0_iter3_reg = exitcond1_i_i_reg_126_pp0_iter2_reg.read();
        exitcond1_i_i_reg_126_pp0_iter4_reg = exitcond1_i_i_reg_126_pp0_iter3_reg.read();
        exitcond1_i_i_reg_126_pp0_iter5_reg = exitcond1_i_i_reg_126_pp0_iter4_reg.read();
        exitcond1_i_i_reg_126_pp0_iter6_reg = exitcond1_i_i_reg_126_pp0_iter5_reg.read();
        exitcond1_i_i_reg_126_pp0_iter7_reg = exitcond1_i_i_reg_126_pp0_iter6_reg.read();
        exitcond1_i_i_reg_126_pp0_iter8_reg = exitcond1_i_i_reg_126_pp0_iter7_reg.read();
        exitcond1_i_i_reg_126_pp0_iter9_reg = exitcond1_i_i_reg_126_pp0_iter8_reg.read();
        i_0_i_i_reg_83_pp0_iter10_reg = i_0_i_i_reg_83_pp0_iter9_reg.read();
        i_0_i_i_reg_83_pp0_iter11_reg = i_0_i_i_reg_83_pp0_iter10_reg.read();
        i_0_i_i_reg_83_pp0_iter12_reg = i_0_i_i_reg_83_pp0_iter11_reg.read();
        i_0_i_i_reg_83_pp0_iter13_reg = i_0_i_i_reg_83_pp0_iter12_reg.read();
        i_0_i_i_reg_83_pp0_iter14_reg = i_0_i_i_reg_83_pp0_iter13_reg.read();
        i_0_i_i_reg_83_pp0_iter15_reg = i_0_i_i_reg_83_pp0_iter14_reg.read();
        i_0_i_i_reg_83_pp0_iter2_reg = i_0_i_i_reg_83_pp0_iter1_reg.read();
        i_0_i_i_reg_83_pp0_iter3_reg = i_0_i_i_reg_83_pp0_iter2_reg.read();
        i_0_i_i_reg_83_pp0_iter4_reg = i_0_i_i_reg_83_pp0_iter3_reg.read();
        i_0_i_i_reg_83_pp0_iter5_reg = i_0_i_i_reg_83_pp0_iter4_reg.read();
        i_0_i_i_reg_83_pp0_iter6_reg = i_0_i_i_reg_83_pp0_iter5_reg.read();
        i_0_i_i_reg_83_pp0_iter7_reg = i_0_i_i_reg_83_pp0_iter6_reg.read();
        i_0_i_i_reg_83_pp0_iter8_reg = i_0_i_i_reg_83_pp0_iter7_reg.read();
        i_0_i_i_reg_83_pp0_iter9_reg = i_0_i_i_reg_83_pp0_iter8_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_reg_130 = i_fu_106_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_reg_126_pp0_iter14_reg.read()))) {
        tmp_2_i_reg_140 = grp_fu_95_p2.read();
    }
}

void mnist_lstm_Loop_1_pr::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void mnist_lstm_Loop_1_pr::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void mnist_lstm_Loop_1_pr::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[2];
}

void mnist_lstm_Loop_1_pr::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_r_TVALID.read()));
}

void mnist_lstm_Loop_1_pr::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_r_TVALID.read()));
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state13_pp0_stage0_iter11() {
    ap_block_state13_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state14_pp0_stage0_iter12() {
    ap_block_state14_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state15_pp0_stage0_iter13() {
    ap_block_state15_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state16_pp0_stage0_iter14() {
    ap_block_state16_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state17_pp0_stage0_iter15() {
    ap_block_state17_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state18_pp0_stage0_iter16() {
    ap_block_state18_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = (esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_r_TVALID.read()));
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void mnist_lstm_Loop_1_pr::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void mnist_lstm_Loop_1_pr::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_ap_phi_mux_i_0_i_i_phi_fu_87_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_reg_126.read()))) {
        ap_phi_mux_i_0_i_i_phi_fu_87_p4 = i_reg_130.read();
    } else {
        ap_phi_mux_i_0_i_i_phi_fu_87_p4 = i_0_i_i_reg_83.read();
    }
}

void mnist_lstm_Loop_1_pr::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_exitcond1_i_i_fu_100_p2() {
    exitcond1_i_i_fu_100_p2 = (!ap_phi_mux_i_0_i_i_phi_fu_87_p4.read().is_01() || !ap_const_lv8_E0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_0_i_i_phi_fu_87_p4.read() == ap_const_lv8_E0);
}

void mnist_lstm_Loop_1_pr::thread_grp_fu_95_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_95_ce = ap_const_logic_1;
    } else {
        grp_fu_95_ce = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_grp_fu_95_p0() {
    grp_fu_95_p0 = in_r_TDATA.read();
}

void mnist_lstm_Loop_1_pr::thread_i_fu_106_p2() {
    i_fu_106_p2 = (!ap_phi_mux_i_0_i_i_phi_fu_87_p4.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(ap_phi_mux_i_0_i_i_phi_fu_87_p4.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void mnist_lstm_Loop_1_pr::thread_img_dat_address0() {
    img_dat_address0 =  (sc_lv<8>) (tmp_i_fu_121_p1.read());
}

void mnist_lstm_Loop_1_pr::thread_img_dat_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()))) {
        img_dat_ce0 = ap_const_logic_1;
    } else {
        img_dat_ce0 = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_img_dat_d0() {
    img_dat_d0 = tmp_2_i_reg_140.read();
}

void mnist_lstm_Loop_1_pr::thread_img_dat_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_reg_126_pp0_iter15_reg.read()))) {
        img_dat_we0 = ap_const_logic_1;
    } else {
        img_dat_we0 = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_in_r_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_0))) {
        in_r_TDATA_blk_n = in_r_TVALID.read();
    } else {
        in_r_TDATA_blk_n = ap_const_logic_1;
    }
}

void mnist_lstm_Loop_1_pr::thread_in_r_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_r_TREADY = ap_const_logic_1;
    } else {
        in_r_TREADY = ap_const_logic_0;
    }
}

void mnist_lstm_Loop_1_pr::thread_tmp_i_fu_121_p1() {
    tmp_i_fu_121_p1 = esl_zext<64,8>(i_0_i_i_reg_83_pp0_iter15_reg.read());
}

void mnist_lstm_Loop_1_pr::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter15.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter15.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(exitcond1_i_i_fu_100_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

